/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  SeasonPassController,
  SeasonPassControllerInterface,
} from "../SeasonPassController";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_tokenAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "_memberAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_gateAmount",
        type: "uint256",
      },
    ],
    name: "checkTokenGate",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506102b9806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80634f4b0ee614610030575b600080fd5b61004a60048036038101906100459190610141565b610060565b60405161005791906101f2565b60405180910390f35b6000818473ffffffffffffffffffffffffffffffffffffffff166370a08231856040518263ffffffff1660e01b815260040161009c91906101d7565b60206040518083038186803b1580156100b457600080fd5b505afa1580156100c8573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906100ec9190610190565b10156100f757600080fd5b600190509392505050565b60008135905061011181610255565b92915050565b6000813590506101268161026c565b92915050565b60008151905061013b8161026c565b92915050565b60008060006060848603121561015657600080fd5b600061016486828701610102565b935050602061017586828701610102565b925050604061018686828701610117565b9150509250925092565b6000602082840312156101a257600080fd5b60006101b08482850161012c565b91505092915050565b6101c28161020d565b82525050565b6101d18161021f565b82525050565b60006020820190506101ec60008301846101b9565b92915050565b600060208201905061020760008301846101c8565b92915050565b60006102188261022b565b9050919050565b60008115159050919050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b6000819050919050565b61025e8161020d565b811461026957600080fd5b50565b6102758161024b565b811461028057600080fd5b5056fea26469706673582212203be45af3074da4f5abe85921cb0ed75249dd8aa801aac11ddee53895cec0bd7e64736f6c63430008040033";

export class SeasonPassController__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<SeasonPassController> {
    return super.deploy(overrides || {}) as Promise<SeasonPassController>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): SeasonPassController {
    return super.attach(address) as SeasonPassController;
  }
  connect(signer: Signer): SeasonPassController__factory {
    return super.connect(signer) as SeasonPassController__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SeasonPassControllerInterface {
    return new utils.Interface(_abi) as SeasonPassControllerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SeasonPassController {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as SeasonPassController;
  }
}
